### ISSUE TITLE
Default value for leave_out_level (leave_out_KSS.m)

### ISSUE THREAD

**Issue by economoser** [rsaggio87/LeaveOutTwoWay#20]
Just flagging a small typo... the following code excerpt from leave_out_KSS.m (version 3.02) should clarify what is the true default:

    %leave_out_level: string variable that takes two values:

        %'obs': perform leave-out by leaving a person-year observation out (default)

        %'matches': perform leave-out by leaving an entire person-firm match out.
    
        %Default: `matches'.

**Comment by rsaggio87** [comment]
thanks! Fixed now.
