### ISSUE TITLE
(Adjusted) R^2

### ISSUE THREAD

**Issue by economoser** [rsaggio87/LeaveOutTwoWay#21]
The new code version 3.02 seems to no longer report the (adjusted) R^2. Could this feature be added? Were the (adjusted) R^2 values in previous code versions faulty? Thanks a lot again :)

**Comment by rsaggio87** [comment]
Thanks for this comment!

There was nothing "wrong" to the Adj R2 that we used to report in previous versions. Just like for the variance of firm effects, the R2 needs to be bias-corrected. The Adj R2 is a popular adjustment but it is based on an assumption of homoskedasticity. We discuss this in the NBER WP version:

![image](https://user-images.githubusercontent.com/22134517/105083340-9d1d7d00-5a49-11eb-9880-a67653986898.png)

The new version of the code prints the total explained variation of the worker+firm dummies (which corresponds to the R2 in a two-way model with no controls) according to the PIug-in method. We also report the same quantify using the leave-out KSS correction which is therefore robust to unrestricted heteroskedasticity.

**Comment by economoser** [comment]
That's very helpful -- thanks! Something I struggle with: when estimating a model with controls that are partialled out first, is there an easy way to compute the bias-corrected R^2? Or would this require bias-correcting all covariates first (which, on a related note, I would find desirable)? If I understand correctly, then in a model with only firm and worker fixed effects but no additional controls, this issue is mute. But obtaining bias-corrected estimates of the variance shares corresponding to controls (and thus the bias-corrected R^2) might be of interest more generally.

**Comment by rsaggio87** [comment]
thank you, this is a great comment and exactly the type of feedback I'm looking for. 

Right now the code does not provide the overall (KSS-adjusted) R2 of the model but it is something that it can be easily added to the next release (gonna leave this issue open to remind myself).
