### ISSUE TITLE
Problem running test.csv with the executable

### ISSUE THREAD

**Issue by simon-lowe** [rsaggio87/LeaveOutTwoWay#25]
Hi,

Thanks a lot for all the work! This is some great stuff! Just starting to try it out and installed your executable and followed all the steps. Everything seems to have installed fine. But when I try to run on the test.csv as suggested in the installation guide, I get the following message:
![image](https://user-images.githubusercontent.com/57216897/121235983-bb1f3900-c895-11eb-8136-5e7249af6558.png)

**Comment by simon-lowe** [comment]
Ok, sorry now that I look at it, this looks like it's looking for the file in the wrong place, which is strange because the installation folder has definitely been added to the path.

**Comment by simon-lowe** [comment]
Ok, never mind, I was being very dumb! Sorry for the bother! Thanks for the great work!

**Comment by rsaggio87** [comment]
no problem at all! Sorry for the late response, for some reason I did not get a notification. Let me know if you run into any other issue. Thanks!
