### ISSUE TITLE
Preserving sparsity adjacency matrix for connected set

### ISSUE THREAD

**Issue by zerecero** [rsaggio87/LeaveOutTwoWay#31]
We have encountered memory issues, particularly when defining the adjacency matrix to find the connected set.
The issue occurs between lines 56 to 61 in connected_set.m, where MATLAB was creating a dense matrix instead of preserving the sparsity.

After replacing those lines with the following code, everything worked smoothly:
if m > n
    A = [A, sparse(m, m - n)];
end
if m < n
    A = [A; sparse(n - m, n)];
end

Thanks a lot for this code!

**Comment by rsaggio87** [comment]
thanks, Miguel, for letting me know. You are right, better to have sparse matrices there. Code has been updated. Thanks again. Raffa.
